VAMPSDK_DIR	:= /home/jvass/Abschlussprojekt/vamp-plugin-sdk

CXXFLAGS	:= -Wall -g -fPIC --std=c++11 -I$(VAMPSDK_DIR)

PLUGIN_LDFLAGS	:= -shared -Wl,-Bsymbolic -Wl,-z,defs -Wl,--version-script=vamp-plugin.map -Wl,-Bstatic $(VAMPSDK_DIR)/libvamp-sdk.a -Wl,-Bdynamic

PLUGIN_EXT	:= .so

MAKEFILE_EXT 	:= .linux

include Makefile.inc


