VAMPSDK_DIR	:= ../../vamp-plugin-sdk

CXXFLAGS	:= -Wall -Wextra -O3 -g -fPIC --std=c++11 -I$(VAMPSDK_DIR)

PLUGIN_LDFLAGS  := -shared -Wl,--no-undefined -Wl,-Bsymbolic -Wl,--version-script=vamp-plugin.map ../../vamp-plugin-sdk/libvamp-sdk.a

PLUGIN_EXT	:= .so

MAKEFILE_EXT 	:= .linux

include Makefile.inc
